### ISSUE TITLE
FileNotFoundException from lang file

### ISSUE THREAD

**Issue by jeremiahwinsley** [Create-Additions/Ponderjs#2]
Using the default lang file location, this error shows up each launch:
```
[11Oct2021 12:17:21.990] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: java.io.FileNotFoundException: kubejs:lang/en_us.json
[11Oct2021 12:17:21.990] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:63)
[11Oct2021 12:17:21.990] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:61)
[11Oct2021 12:17:21.990] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at com.kotakotik.ponderjs.PonderJS.getKubeJSAssetLang(PonderJS.java:155)
[11Oct2021 12:17:21.990] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at com.kotakotik.ponderjs.PonderJS.fillPonderLang(PonderJS.java:172)
[11Oct2021 12:17:21.990] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at com.kotakotik.ponderjs.PonderJS.fillPonderLang(PonderJS.java:184)
[11Oct2021 12:17:21.990] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at com.kotakotik.ponderjs.PonderRegistryEventJS.regenerateLangIntoFile(PonderRegistryEventJS.java:39)
[11Oct2021 12:17:21.990] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at com.kotakotik.ponderjs.PonderRegistryEventJS.regenerateLang(PonderRegistryEventJS.java:58)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at com.kotakotik.ponderjs.PonderRegistryEventJS.runAllRegistration(PonderRegistryEventJS.java:72)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at com.kotakotik.ponderjs.PonderRegistryEventJS.lambda$register$0(PonderRegistryEventJS.java:83)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$1(DeferredWorkQueue.java:80)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:78)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$0(DeferredWorkQueue.java:73)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:73)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraftforge.fml.ModLoadingStage.lambda$null$7(ModLoadingStage.java:78)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11Oct2021 12:17:21.991] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[11Oct2021 12:17:21.992] [Render thread/INFO] [STDERR/]: [com.kotakotik.ponderjs.PonderJS:getKubeJSAssetLang:159]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by kotakotik22** [comment]
this shouldnt break anything, but it will be fixed in the next version
